### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danielberlin**
`git clone git@github.com:user/tvb-pack tvb` gives: "ERROR: Repository not found."
while `git clone git@github.com:the-virtual-brain/tvb-pack.git tvb` does work.

(Because GITHub itself favors the clone url with suffix .git, it should be preferred over `git@github.com:the-virtual-brain/tvb-pack` which also works.)

### CODE REVIEW

**Comment by maedoc** [comment]
> `...user/tvb-pack tvb` gives: "ERROR:"

The instructions are fairly explicit: replace `user` by your GitHub username. The intention of this repo is to allow a given scientific project to track specific versions of the TVB libraries it is using, so `git clone https://github.com/the-virtual-brain/tvb-pack` is a practice I specifically wish to _discourage_.

This intention is perhaps not fairly obvious from the README, so that may be a bug worth fixing.

> GITHub itself favors the clone url with suffix .git

This is technically true, but there are a few subjective reasons I don't use the `.git` postfix

- GitHub rewrites URLs correctly and always will, given that everyone mixes these
- 4 characters I don't have to type when using a terminal
- the public https clone URL is identical to the repo website

Again, since GitHub rewrites URLs where needed, you choose your favorite.

**Comment by danielberlin** [comment]
I should've been more detailed:
If I don't fork it (because the README doesn't tell me do to so!), `git clone https://github.com/myusername/tvb-pack` doesn't work even with my username. But we've already agreed that the README should be more clear to show this intention.

**Comment by maedoc** [comment]
@danielberlin 

https://github.com/the-virtual-brain/tvb-pack/blob/master/README.md

look ok?

**Comment by danielberlin** [comment]
Great, but now I was convinced not to use .git suffixes and you introduced them. Is it also intended to first have the http clone URL and for the second example, use the SSH one? I'm always a fan of least confusion. :-)

**Comment by maedoc** [comment]
lol

https is a public clone url, while ssh works with the keys you register on GitHub, so generally more convenient.

**Pull request closed without merging**
